name: VIP Customer Deployment Workflow
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  build-push-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Build Frontend Image
        run: |
          docker build ./frontend -t vip-customer-web:v1
          docker tag vip-customer-web:v1 kennedyuche/vip-customer-web:v1
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vip-customer-web:v1
      
      - name: Login to Azure Kubernetes
        run: |
          az login --service-principal -u ${{ secrets.AZ_CLIENT_ID }} -p ${{ secrets.AZ_CLIENT_SECRET }} --tenant ${{ secrets.AZ_TENANT_ID }}
          az aks get-credentials --resource-group ${{ secrets.AZ_RESOURCE_GROUP }} --name ${{ secrets.AZ_CLUSTER }}
          kubectl apply -f ./kubernetes/
          kubectl rollout restart deployment vip-customer-web -n vip-customer-app

      - name: Deploy Application
        run: |
          kubectl apply -f ./deployment/
          kubectl rollout restart deployment vip-customer-web -n vip-customer-app